### ISSUE TITLE
Python Wrapping fails on Windows

### ISSUE THREAD

**Issue by MrTzschr** [RTKConsortium/ITKCudaCommon#30]
Hi,

I want to build RTK and included CudaCommon in the CMake flags:
```
cmake -DBUILD_SHARED_LIBS:BOOL=OFF -DBUILD_EXAMPLES:BOOL=OFF -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_TESTING:BOOL=OFF -DModule_CudaCommon:BOOL=ON -DModule_CudaCommon_GIT_TAG:STRING=v1.0.1 -DITK_WRAP_PYTHON:BOOL=ON -GNinja ../ITK-src
```

This compiles but calling the module from python ends with the following error:

```
import itk
itk.CudaImage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ITK\test\Wrapping\Generators\Python\itk\support\lazy.py", line 138, in __getattribute__
    base.itk_load_swig_module(module, namespace)
  File "C:\ITK\test\Wrapping\Generators\Python\itk\support\base.py", line 132, in itk_load_swig_module
    l_module = loader.load(swig_module_name)
  File "C:\ITK\test\Wrapping\Generators\Python\itk\support\base.py", line 291, in load
    l_spec.loader.exec_module(l_module)  # pytype: disable=attribute-error
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\ITK\test\Wrapping\Generators\Python\itk\support\..\CudaCommonPython.py", line 13, in <module>
    from . import _CudaCommonPython
ImportError: DLL load failed while importing _CudaCommonPython: Das angegebene Modul wurde nicht gefunden.
>>>
```
When building RTK this also triggers the same error by calling `rtk.Image`.
I tried a similar build in WSL running Ubuntu, but with python 3.10.12, and there the module loads without issues so I suspect an issue with the relative import path "itk\support\\..\CudaCommonPython.py" on Windows.

My environment is:
Windows 10
VS 2019 v16.11.32
Python v3.8.18
Ninja v1.11.1

**Comment by SimonRit** [comment]
Have you tried to run the FirstCudaReconstruction.py example or to execute this first
https://github.com/RTKConsortium/RTK/blob/master/examples/FirstReconstruction/FirstCudaReconstruction.py#L13-L14?

**Comment by MrTzschr** [comment]
Works!
Is there a recommend way to solve this without added these lines to the python code, e.g. modifying the PATH variable?

**Comment by SimonRit** [comment]
I'm not an expert of Windows+Python+DLL but if you look at https://docs.python.org/3.8/whatsnew/3.8.html#bpo-36085-whatsnew, you could copy the required Cuda DLLs to "the system paths, the directory containing the DLL or PYD file, and directories added with [add_dll_directory()](https://docs.python.org/3.8/library/os.html#os.add_dll_directory)"
